services:
  postgres_superset_link:
    extends:
      file: ./docker_foundation/postgres/docker-compose.yaml
      service: postgres_superset_link
    volumes:
    - ./createDemoTable.sql:/docker-entrypoint-initdb.d/createDemoTable.sql
    - postgres_data:/var/lib/postgresql/data
    networks:
    - superset_link_network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "superset_link", "-h", "localhost", "-p", "5432" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

networks:
  superset_link_network:

volumes:
  postgres_data: