services:
  postgres_superset_link:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: superset_link
    ports:
    - "5437:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - my_network

networks:
  my_network:

volumes:
  postgres_data: