services:
  postgres_superset_link:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: superset_link
    ports:
    - "5437:5432"
    volumes:
    - ./createDemoTable.sql:/docker-entrypoint-initdb.d/createDemoTable.sql
    - postgres_data:/var/lib/postgresql/data
    networks:
    - superset_link_network

networks:
  superset_link_network:

volumes:
  postgres_data: